In [1]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
#import pandas as pd
import astropy.io.fits as fits
#from astropy import units as u
#from astropy import constants as const


plt.style.use(['science'])#,'no-latex'])

#load cosmolike interface tools
import sys
sys.path.append('../2pt_modified/')

import cosmolike_metadata
import twopoint



In [35]:
filename = "../6x2pt_Roman_SO_v1_2_bf26108.fits"

two_point_data = twopoint.TwoPointFile.from_fits(filename)
#cosmosis = loop_comosis_datavector(two_point_data)

In [10]:
covmat = two_point_data.covmat#_info
covmat.shape

(2360, 2360)

In [11]:
#inverting works
np.linalg.inv(covmat)

array([[ 3.30711111e+18, -1.98058247e+16, -2.54157471e+16, ...,
        -1.49738041e+15, -9.37743139e+14, -3.62717567e+14],
       [-1.98058247e+16,  6.87697800e+18, -4.37552252e+16, ...,
        -2.58516745e+15, -1.62031234e+15, -6.25813709e+14],
       [-2.54157471e+16, -4.37552252e+16,  1.19792974e+19, ...,
        -3.75596689e+15, -2.34405975e+15, -9.02783130e+14],
       ...,
       [-1.49738041e+15, -2.58516745e+15, -3.75596688e+15, ...,
         1.31591418e+19,  1.17143617e+16,  4.39756602e+15],
       [-9.37743139e+14, -1.62031234e+15, -2.34405975e+15, ...,
         1.17143617e+16,  1.08280463e+19,  2.67802223e+15],
       [-3.62717567e+14, -6.25813710e+14, -9.02783132e+14, ...,
         4.39756602e+15,  2.67802223e+15,  5.76791522e+18]])

In [39]:
covmat_samearea = np.copy(covmat)

#kappa kappa is covmat[2340:, 2340:]
#rescale to same area
covmat_samearea[:,2340: ] = np.sqrt(0.0484813681/0.4) * covmat_samearea[:,2340: ]
covmat_samearea[2340: , :] = np.sqrt(0.0484813681/0.4) * covmat_samearea[2340:, : ]


#inverting works
np.linalg.inv(covmat_samearea)

array([[ 3.30711111e+18, -1.98058247e+16, -2.54157471e+16, ...,
        -4.30105215e+15, -2.69355878e+15, -1.04186429e+15],
       [-1.98058247e+16,  6.87697800e+18, -4.37552252e+16, ...,
        -7.42559472e+15, -4.65415993e+15, -1.79757755e+15],
       [-2.54157471e+16, -4.37552252e+16,  1.19792974e+19, ...,
        -1.07885808e+16, -6.73304070e+15, -2.59314020e+15],
       ...,
       [-4.30105215e+15, -7.42559472e+15, -1.07885807e+16, ...,
         1.08570713e+20,  9.66504221e+16,  3.62825241e+16],
       [-2.69355878e+15, -4.65415993e+15, -6.73304071e+15, ...,
         9.66504221e+16,  8.93377951e+19,  2.20952694e+16],
       [-1.04186429e+15, -1.79757755e+15, -2.59314020e+15, ...,
         3.62825241e+16,  2.20952694e+16,  4.75887166e+19]])

In [36]:
covmat_uselargearea = np.copy(covmat)

#kappa kappa is covmat[2340:, 2340:]
#rescale to same area
covmat_uselargearea[:2340,2340: ] = np.sqrt(0.4/0.0484813681) * covmat_uselargearea[:2340,2340: ]
covmat_uselargearea[2340: , :2340] = np.sqrt(0.4/0.0484813681) * covmat_uselargearea[2340:, :2340 ]


#inverting works
np.linalg.inv(covmat_uselargearea)

array([[ 3.30709437e+18, -1.98350296e+16, -2.54581853e+16, ...,
        -4.70294477e+15, -2.54475156e+15, -9.17764613e+14],
       [-1.98350296e+16,  6.87692703e+18, -4.38292892e+16, ...,
        -8.09931013e+15, -4.38735610e+15, -1.57967826e+15],
       [-2.54581853e+16, -4.38292892e+16,  1.19791898e+19, ...,
        -1.17634530e+16, -6.33961727e+15, -2.27499933e+15],
       ...,
       [-4.70294477e+15, -8.09931013e+15, -1.17634530e+16, ...,
         1.75450854e+19,  1.16585166e+17,  4.05312274e+16],
       [-2.54475156e+15, -4.38735611e+15, -6.33961728e+15, ...,
         1.16585166e+17,  1.22942465e+19,  2.12134894e+16],
       [-9.17764613e+14, -1.57967826e+15, -2.27499934e+15, ...,
         4.05312274e+16,  2.12134894e+16,  6.04711526e+18]])

In [37]:
np.linalg.cholesky(covmat_uselargearea)

LinAlgError: Matrix is not positive definite

In [38]:
np.all(np.linalg.eigvals(covmat_uselargearea) > 0)

False

In [31]:
np.all(np.linalg.eigvals(covmat) > 0)

True

In [32]:
np.all(np.linalg.eigvals(covmat_samearea) > 0)

True

In [40]:
np.linalg.cholesky(covmat)

array([[ 8.82423910e-10,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.15997012e-11,  5.62470448e-10,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.29046182e-11,  2.51424751e-11,  3.93470956e-10, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 1.76372521e-13,  1.96773995e-13,  1.96075148e-13, ...,
         2.75668080e-10,  0.00000000e+00,  0.00000000e+00],
       [ 1.11374466e-13,  1.24446607e-13,  1.24061072e-13, ...,
        -2.98180580e-13,  3.03895992e-10,  0.00000000e+00],
       [ 6.92062802e-14,  7.74102246e-14,  7.72159208e-14, ...,
        -2.10036036e-13, -1.41097813e-13,  4.16380676e-10]])

In [49]:
covmat_zero = np.copy(covmat)

#kappa kappa is covmat[2340:, 2340:]
#rescale to same area
covmat_zero[:2340,2340: ] = 0. * covmat_zero[:2340,2340: ]
covmat_zero[2340: , :2340] = 0. * covmat_zero[2340:, :2340 ]


#inverting works
np.linalg.inv(covmat_zero)

array([[ 3.30710473e+18, -1.98169999e+16, -2.54320557e+16, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.98169999e+16,  6.87695840e+18, -4.37838219e+16, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.54320558e+16, -4.37838219e+16,  1.19792557e+19, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         1.27161408e+19, -1.84703102e+14, -6.45909162e+13],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.84703102e+14,  1.06512020e+19, -3.94071352e+13],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -6.45909162e+13, -3.94071352e+13,  5.73118974e+18]])

In [51]:
np.all(np.linalg.eigvals(covmat_zero) > 0)

True

In [50]:
covmat_zero[-1, 0]

0.0

In [45]:
covmat_samearea[-1, 0]

2.126082981345376e-23

In [46]:
covmat[-1, 0]

6.106927629574209e-23

In [52]:
np.linalg.cholesky(covmat_zero)

array([[8.82423910e-10, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.15997012e-11, 5.62470448e-10, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.29046182e-11, 2.51424751e-11, 3.93470956e-10, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.80428621e-10, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        4.86294042e-15, 3.06408416e-10, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.16048395e-15, 2.10683618e-15, 4.17712630e-10]])

In [56]:
#safe to test datavector
from astropy.io import fits
fits_image_filename = "../6x2pt_Roman_SO_v1_2_bf26108.fits"
hdul = fits.open(fits_image_filename)
hdul.info()

Filename: ../6x2pt_Roman_SO_v1_2_bf26108.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()      
  1  COVMAT        1 ImageHDU        21   (2360, 2360)   float64   
  2  shear_cl      1 BinTableHDU     28   1100R x 5C   [K, K, K, D, D]   
  3  galaxy_shear_cl    1 BinTableHDU     28   640R x 5C   [K, K, K, D, D]   
  4  shear_cmbkappa_cl    1 BinTableHDU     28   200R x 5C   [K, K, K, D, D]   
  5  galaxy_cl     1 BinTableHDU     28   200R x 5C   [K, K, K, D, D]   
  6  galaxy_cmbkappa_cl    1 BinTableHDU     28   200R x 5C   [K, K, K, D, D]   
  7  cmbkappa_cl    1 BinTableHDU     28   20R x 5C   [K, K, K, D, D]   
  8  nz_source     1 BinTableHDU     36   300R x 13C   [D, D, D, D, D, D, D, D, D, D, D, D, D]   
  9  nz_lens       1 BinTableHDU     36   300R x 13C   [D, D, D, D, D, D, D, D, D, D, D, D, D]   


In [57]:
hdul[1].data[-1, 0]

6.106927629574209e-23

In [58]:
hdul[1].data = covmat_zero

In [59]:
hdul[1].data[-1, 0]

0.0

In [60]:
hdul.writeto('../6x2pt_Roman_SO_v1_2_bf26108_zerobetweensurveysRAW.fits')